#!/bin/bash
if [ -z IC_API_KEY ]; then
    "please set the environment variable IC_API_KEY with an account API KEY"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/vpcs

for d in */; do
    cd $d
    terraform init > /dev/null 2>&1 &
    cd ..
done

cd $DIR